"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.18.

Configuración por entorno (PE-6): todos los valores sensibles llegan por
variables de entorno. Ver `.env.example` con el listado y valores de ejemplo.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Modo depuración ---------------------------------------------------------
# Por defecto DEBUG es False. Solo se activa de forma explícita con
# DJANGO_DEBUG=1 (desarrollo local). En ningún otro caso se enciende.
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

# --- Clave secreta -----------------------------------------------------------
# Obligatoria: no existe valor por defecto en el repositorio. Django la exige
# para firmar sesiones, tokens CSRF y mensajes. Si falta, Django (y los tests)
# fallan de forma explícita con KeyError en lugar de usar una clave known.
if DEBUG:
    # Excepción única: con DJANGO_DEBUG=1 se admite una clave de desarrollo
    # local, dejándola claramente marcada como NO válida para producción.
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "clave-solo-desarrollo-local-NO-USAR-en-produccion-DJANGO_DEBUG=1",
    )
else:
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# --- Hosts permitidos --------------------------------------------------------
# Lista separada por coma: DJANGO_ALLOWED_HOSTS="localhost,127.0.0.1"
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps del dominio del panel (PE-6; la lógica llega en PE-14)
    'catalogo',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# PostgreSQL solo si están definidas las 5 variables de conexión; en caso
# contrario se usa SQLite local (db.sqlite3, ignorado por Git).
# La conexión a PostgreSQL real NO está verificada en esta tarea (PE-6).

_POSTGRES_VARS = ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT")

if all(os.environ.get(name) for name in _POSTGRES_VARS):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ["DB_NAME"],
            'USER': os.environ["DB_USER"],
            'PASSWORD': os.environ["DB_PASSWORD"],
            'HOST': os.environ["DB_HOST"],
            'PORT': os.environ["DB_PORT"],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
